name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: nix
      run: |
        curl https://nixos.org/nix/install | sh
        . "$HOME"/.nix-profile/etc/profile.d/nix.sh
        cargo build --verbose
        cargo test --verbose
